// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aynhvozryqdfoibmhygq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bmh2b3pyeXFkZm9pYm1oeWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODY4MTcsImV4cCI6MjA3MTc2MjgxN30.JX1fqDKVo4vKk8gWpscN_if8kZbH3N2liX2TnIfingk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});